### PR TITLE
Refactor doc toolchain

### PR DESCRIPTION
**Pull request by guyboltonking**
This moves the WORKSPACE deps around, changes the doc toolchain to remove copied code and undocumented deps, and pulls some rules to the top-level (for easier development).

### CODE REVIEW

**Comment by guyboltonking** [comment]
Current dependencies on/for this PR:
* main
  * **PR #33** <a href="https://app.graphite.dev/github/pr/DataDog/rules_oci/33" target="_blank">Graphite</a> 
    * **PR #34** <a href="https://app.graphite.dev/github/pr/DataDog/rules_oci/34" target="_blank">Graphite</a> 
    * **PR #36** <a href="https://app.graphite.dev/github/pr/DataDog/rules_oci/36" target="_blank">Graphite</a>  👈
      * **PR #37** <a href="https://app.graphite.dev/github/pr/DataDog/rules_oci/37" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/DataDog/rules_oci/36?utm_source=stack-comment).

**Review by jprobinson — APPROVED** [review]
📜 🌯

**Comment by guyboltonking** [comment]
@guyboltonking queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/DataDog/rules_oci/36).

**Comment by guyboltonking** [comment]
@guyboltonking merged this pull request with [Graphite](https://app.graphite.dev/github/pr/DataDog/rules_oci/36).

**Pull request merged**
